services:
  app:
    container_name: pysakoinnin-sahk-asiointi-ui
    build:
      context: .
      secrets:
        - SENTRY_AUTH_TOKEN
    volumes:
      - '.:/app'
    ports:
      - '3000:3000'
    stdin_open: true
    env_file:
      - .env
secrets:
  SENTRY_AUTH_TOKEN:
    environment: SENTRY_AUTH_TOKEN