version: '3.7'

services:
  app:
    container_name: pysakoinnin-sahk-asiointi-ui
    build:
      context: .
      target: ${DOCKER_TARGET:-development}
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    stdin_open: true
    env_file:
      - .env.development
